spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_sim
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-postgres.sql
      data-locations: classpath:data-postgres.sql
      continue-on-error: false
