-- =====================================================================
-- data-postgres.sql
-- PostgreSQL draft seed data for the payment simulator.
--
-- This file intentionally does not replace db/data.sql.
-- =====================================================================

INSERT INTO BIN_CATALOG (
    BIN,
    BRAND,
    ISSUER,
    COUNTRY,
    BIN_LEN,
    ACTIVE_YN,
    CREATED_AT,
    UPDATED_AT
)
VALUES
    ('41111111', 'VISA',   'KB_CARD_TEST',       'KR', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('42222222', 'VISA',   'SHINHAN_CARD_TEST',  'KR', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('43333333', 'VISA',   'HYUNDAI_CARD_TEST',  'KR', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('44444444', 'VISA',   'LOTTE_CARD_TEST',    'KR', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('45555555', 'VISA',   'WOORI_CARD_TEST',    'KR', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('51111111', 'MASTER', 'KB_CARD_TEST',       'KR', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('52222222', 'MASTER', 'SHINHAN_CARD_TEST',  'KR', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('53333333', 'MASTER', 'HYUNDAI_CARD_TEST',  'KR', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('54444444', 'MASTER', 'LOTTE_CARD_TEST',    'KR', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('55555555', 'MASTER', 'WOORI_CARD_TEST',    'KR', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('61111111', 'LOCAL',  'BC_CARD_TEST',       'KR', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('62222222', 'LOCAL',  'NH_CARD_TEST',       'KR', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('63333333', 'LOCAL',  'HANA_CARD_TEST',     'KR', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('37111111', 'AMEX',   'AMEX_TEST',          'US', 8, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    ('49999999', 'VISA',   'INACTIVE_CARD_TEST', 'KR', 8, 'N', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (BIN) DO UPDATE SET
    BRAND = EXCLUDED.BRAND,
    ISSUER = EXCLUDED.ISSUER,
    COUNTRY = EXCLUDED.COUNTRY,
    BIN_LEN = EXCLUDED.BIN_LEN,
    ACTIVE_YN = EXCLUDED.ACTIVE_YN,
    UPDATED_AT = CURRENT_TIMESTAMP;
