-- =====================================================================
-- schema-postgres.sql
-- PostgreSQL schema for the VAN simulator.
-- =====================================================================

CREATE TABLE IF NOT EXISTS van_approval
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    van_trx_id      VARCHAR(50) NOT NULL,
    pos_trx         VARCHAR(23) NOT NULL,
    attempt_seq     INTEGER     NOT NULL,
    amount          INTEGER     NOT NULL,
    card_bin        VARCHAR(8)  NOT NULL,
    card_last4      VARCHAR(4)  NOT NULL,
    approval_status VARCHAR(20) NOT NULL,
    approval_no     VARCHAR(20),
    decline_code    VARCHAR(20),
    processed_at    TIMESTAMP   NOT NULL,

    CONSTRAINT uk_van_approval_van_trx_id UNIQUE (van_trx_id),
    CONSTRAINT uk_van_approval_pos_trx_attempt_seq UNIQUE (pos_trx, attempt_seq),
    CONSTRAINT ck_van_approval_attempt_seq_positive CHECK (attempt_seq > 0),
    CONSTRAINT ck_van_approval_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_van_approval_status CHECK (approval_status IN ('APPROVED', 'DECLINED', 'UNKNOWN')),
    CONSTRAINT ck_van_approval_status_payload CHECK (
        (approval_status = 'APPROVED' AND approval_no IS NOT NULL AND decline_code IS NULL)
            OR (approval_status = 'DECLINED' AND approval_no IS NULL AND decline_code IS NOT NULL)
            OR (approval_status = 'UNKNOWN' AND approval_no IS NULL AND decline_code IS NULL)
    )
);

CREATE TABLE IF NOT EXISTS van_cancel
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    van_cancel_trx_id       VARCHAR(50) NOT NULL,
    cancel_pos_trx          VARCHAR(23) NOT NULL,

    original_pos_trx        VARCHAR(23) NOT NULL,
    original_attempt_seq    INTEGER     NOT NULL,
    original_van_trx_id     VARCHAR(50) NOT NULL,
    original_approval_no    VARCHAR(20) NOT NULL,

    amount                  INTEGER     NOT NULL,

    cancel_status           VARCHAR(20) NOT NULL,
    cancel_approval_no      VARCHAR(20),
    decline_code            VARCHAR(20),

    processed_at            TIMESTAMP   NOT NULL,

    CONSTRAINT uk_van_cancel_van_cancel_trx_id
    UNIQUE (van_cancel_trx_id),

    CONSTRAINT uk_van_cancel_cancel_pos_trx
    UNIQUE (cancel_pos_trx),

    CONSTRAINT uk_van_cancel_original
    UNIQUE (original_pos_trx, original_attempt_seq),

    CONSTRAINT ck_van_cancel_amount_positive
    CHECK (amount > 0),

    CONSTRAINT ck_van_cancel_status
    CHECK (
              cancel_status IN ('CANCELLED', 'CANCEL_DECLINED')
    ),

    CONSTRAINT ck_van_cancel_status_payload
    CHECK (
        (
              cancel_status = 'CANCELLED'
              AND cancel_approval_no IS NOT NULL
              AND decline_code IS NULL
        )
    OR
        (
            cancel_status = 'CANCEL_DECLINED'
            AND cancel_approval_no IS NULL
            AND decline_code IS NOT NULL
        )
    )

);

CREATE TABLE IF NOT EXISTS van_reversal
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    van_reversal_trx_id         VARCHAR(50) NOT NULL,
    reversal_pos_trx            VARCHAR(23) NOT NULL,

    original_pos_trx            VARCHAR(23) NOT NULL,
    original_attempt_seq        INTEGER     NOT NULL,

    amount                      INTEGER     NOT NULL,

    reversal_status             VARCHAR(30) NOT NULL,
    reversal_approval_no        VARCHAR(20),
    decline_code                VARCHAR(30),

    processed_at                TIMESTAMP   NOT NULL,

    CONSTRAINT uk_van_reversal_van_reversal_trx_id
    UNIQUE (van_reversal_trx_id),

    CONSTRAINT uk_van_reversal_reversal_pos_trx
    UNIQUE (reversal_pos_trx),

    CONSTRAINT uk_van_reversal_original
    UNIQUE (original_pos_trx, original_attempt_seq),

    CONSTRAINT ck_van_reversal_original_attempt_seq_positive
    CHECK (original_attempt_seq > 0),

    CONSTRAINT ck_van_reversal_amount_positive
    CHECK (amount > 0),

    CONSTRAINT ck_van_reversal_status
    CHECK (
              reversal_status IN ('REVERSED', 'REVERSAL_DECLINED')
    ),

    CONSTRAINT ck_van_reversal_status_payload
    CHECK (
        (
              reversal_status = 'REVERSED'
              AND reversal_approval_no IS NOT NULL
              AND decline_code IS NULL
        )
    OR
        (
            reversal_status = 'REVERSAL_DECLINED'
            AND reversal_approval_no IS NULL
            AND decline_code IS NOT NULL
        )
    )

);
